<?php
/**
 * created : 10/03/2011
 *
 * @category  Ayaline
 * @package   Ayaline_Shop
 * @author    aYaline
 * @copyright Ayaline - 2012 - http://magento-shop.ayaline.com
 * @license   http://shop.ayaline.com/magento/fr/conditions-generales-de-vente.html
 */

/**
 * @see Ayaline_Shop_Block_View
 */
?>
<?php $_shop = $this->getShop() ?>
<div class="bandeau-right-one-in white-back">
    <div class="box-right-one-in">
        <p class="bloc-parag">
            <?php echo $this->__('Find the shop nearest you by clicking on the interactive map or the full list of shops') ?>
        </p>

        <div>
            <div class="float-left">
                <div><?php echo $this->getChildHtml('shops_map_view') ?></div>
            </div>
            <div class="float-left">
                <div class="box-bis-shops view-shop">
                    <h4><?php echo $this->__("Shop's informations") ?></h4>

                    <div class="shop-view-content">
                        <div class="shop-view-content-line shop-view-title-container">
                            <div class="shop-view-title"><?php echo $_shop->getTitle() ?></div>
                            <?php $_icon = $_shop->getShopGroup()->getIcon() ?>
                            <?php if ($_icon) : ?>
                                <div class="shop-view-group">
                                    <img src="<?php echo $_icon ?>">
                                </div>
                            <?php endif; ?>
                            <div class="clear"></div>
                        </div>

                        <div class="shop-view-content-line">
                            <div class="shop-view-description float-left"><?php echo $_shop->getDescription() ?></div>
                            <div class="clear"></div>
                        </div>

                        <div class="shop-view-content-line">
                            <div class="shop-view-address-title"><?php echo $this->__('Coordinates') ?>
                                &nbsp;:&nbsp;</div>
                            <?php if ($_shop->getStreet1()) : ?>
                                <div class="shop-view-address-line"><?php echo $_shop->getStreet1() ?></div>
                            <?php endif; ?>

                            <?php if ($_shop->getStreet2()) : ?>
                                <div class="shop-view-address-line"><?php echo $_shop->getStreet2() ?></div>
                            <?php endif; ?>
                            <div class="shop-view-address-line"><?php echo $_shop->getPostcode() ?>
                                &nbsp;<?php echo $_shop->getCity() ?></div>
                            <?php if ($_shop->getTelephone()) : ?>
                                <div class="shop-view-address-line"><?php echo $this->__('Tel') ?>
                                    &nbsp;:&nbsp;<?php echo $_shop->getTelephone() ?></div>
                            <?php endif; ?>
                            <?php if ($_shop->getFax()) : ?>
                                <div class="shop-view-address-line"><?php echo $this->__('Fax') ?>
                                    &nbsp;:&nbsp;<?php echo $_shop->getFax() ?></div>
                            <?php endif; ?>
                            <?php if ($_shop->getEmail()) : ?>
                                <?php $email = explode(',', $_shop->getEmail()); ?>
                                <div class="shop-view-address-line">
                                    <?php foreach ($email as $_email): ?>
                                        <?php echo $_email; ?><br/>
                                    <?php endforeach; ?>
                                </div>
                            <?php endif; ?>
                            <?php if ($_shop->getWebsite()) : ?>
                                <div class="shop-view-address-line"><a href="<?php echo $_shop->getWebsite() ?>"
                                                                       target="_bank"><?php echo $_shop->getWebsite() ?></a>
                                </div>
                            <?php endif; ?>
                        </div>

                        <div class="shop-view-content-line">
                            <div class="shop-view-schedules-title"><?php echo $this->__('Opening hours') ?>
                                &nbsp;:&nbsp;</div>
                            <div class="shop-view-schedules-list">
                                <table border="0" cellpadding="0" cellspacing="0" class="shop-view-schedules-tab">
                                    <tbody>
                                    <?php foreach ($_shop->getSchedules() as $_schedules) : ?>
                                        <?php $_hasHourPm = ($_schedules->getHourStartPm() && $_schedules->getHourEndPm()) ?>
                                        <?php $_hasHourAm = ($_schedules->getHourStartAm() && $_schedules->getHourEndAm()) ?>
                                        <?php if ($_hasHourPm || $_hasHourAm) : ?>
                                            <tr>
                                                <td class="day"><?php echo $_schedules->getDay() ?></td>
                                                <td class="schedules">
                                                    <?php if ($_hasHourPm) : ?>
                                                        <?php echo $_schedules->getHourStartPm() ?>-<?php echo $_schedules->getHourEndPm() ?>
                                                    <?php endif; ?>
                                                    <?php if ($_hasHourPm && $_hasHourAm) : ?>
                                                        /
                                                    <?php endif; ?>
                                                    <?php if ($_hasHourAm) : ?>
                                                        <?php echo $_schedules->getHourStartAm() ?>-<?php echo $_schedules->getHourEndAm() ?>
                                                    <?php endif; ?>
                                                </td>
                                            </tr>
                                        <?php endif; ?>
                                    <?php endforeach; ?>
                                    </tbody>
                                </table>
                            </div>
                        </div>

                        <?php $_specialSchedules = $_shop->getSpecialsSchedules() ?>
                        <?php if ($_specialSchedules->getSize()) : ?>
                            <div class="shop-view-content-line">
                                <div class="shop-view-schedules-title"><?php echo $this->__('Special opening hours') ?>
                                    &nbsp;:&nbsp;</div>
                                <div class="shop-view-schedules-list">
                                    <table border="0" cellpadding="0" cellspacing="0" class="shop-view-schedules-tab">
                                        <tbody>
                                        <?php foreach ($_specialSchedules as $_schedules) : ?>
                                            <?php $_hasHourPm = ($_schedules->getHourStartPm() && $_schedules->getHourEndPm()) ?>
                                            <?php $_hasHourAm = ($_schedules->getHourStartAm() && $_schedules->getHourEndAm()) ?>
                                            <?php if ($_hasHourPm || $_hasHourAm) : ?>
                                                <tr>
                                                    <td><?php echo $_schedules->getDay() ?></td>
                                                    <td>
                                                        <div class="specials-schedules">
                                                            <?php if ($_hasHourPm) : ?>
                                                                <?php echo $_schedules->getHourStartPm() ?>-<?php echo $_schedules->getHourEndPm() ?>
                                                            <?php endif; ?>
                                                            <?php if ($_hasHourPm && $_hasHourAm) : ?>
                                                                /
                                                            <?php endif; ?>
                                                            <?php if ($_hasHourAm) : ?>
                                                                <?php echo $_schedules->getHourStartAm() ?>-<?php echo $_schedules->getHourEndAm() ?>
                                                            <?php endif; ?>
                                                        </div>
                                                    </td>
                                                </tr>
                                            <?php endif; ?>
                                        <?php endforeach; ?>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        <?php endif; ?>
                        <?php if ($_shop->getPicture()) : ?>
                            <div class="shop-view-content-line">
                                <a href="<?php echo $_shop->getPicture() ?>" rel="lightbox"><img
                                        src="<?php echo $_shop->getPicture() ?>"
                                        title="<?php echo $_shop->getTitle() ?>" width="114" height="90"/></a>
                            </div>
                        <?php endif; ?>
                        <div class="shop-view-content-line shop-view-back-link">
                            <div class="float-right link-all-shops">
                                <a href="<?php echo $this->escapeUrl($this->getUrl('*/*')) ?>"><?php echo $this->__('all the shops') ?>
                                    &nbsp;&gt;&gt;</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="clear"></div>
        </div>

    </div>
</div>

<script type="text/javascript">
    //<![CDATA[
    LightboxOptions = Object.extend({
        fileLoadingImage: '<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>',
        fileBottomNavCloseImage: '<?php echo $this->getSkinUrl('images/closelabel.gif') ?>',

        overlayOpacity: 0.8,   // controls transparency of shadow overlay

        animate: true,         // toggles resizing animations
        resizeSpeed: 7,        // controls the speed of the image resizing animations (1=slowest and 10=fastest)

        borderSize: 10,         //if you adjust the padding in the CSS, you will need to update this variable

        // When grouping images this is used to write: Image # of #.
        // Change it for non-english localization
        labelImage: "<?php echo $_shop->getTitle()?>",
        labelOf: "of"
    }, window.LightboxOptions || {});
    //]]>
</script>