<?php
/* 
<script type="text/javascript">
    var myScroll;
    function loaded() {
        //myScroll = new iScroll('wrapper', {checkDOMChanges:true, hScrollbar:false, vScrollbar:true,hideScrollbar: true,scrollbarClass: 'myScrollbar' });
    }
    document.addEventListener('touchmove', function (e) { e.preventDefault(); }, false);
    document.addEventListener('DOMContentLoaded', loaded, false);

</script> 
    */