<?php
/**
 * created : 2014
 *
 * @category  Ayaline
 * @package   Ayaline_EnhancedAdmin
 * @author    aYaline
 * @copyright Ayaline - 2014 - http://magento-shop.ayaline.com
 * @license   http://shop.ayaline.com/magento/fr/conditions-generales-de-vente.html
 */

/** @var $this Ayaline_EnhancedAdmin_Block_Adminhtml_Setup_Actions */

?>
<div class="content-header">
    <h3 class="icon-head head-"><?php echo $this->__('Actions'); ?></h3>
</div>
<div class="entry-edit">
    <?php foreach ($this->getActions() as $_groupKey => $_group): ?>
        <div class="entry-edit-head">
            <h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->escapeHtml($_group['name']); ?></h4>
        </div>

        <div class="fieldset fieldset-wide">
            <div class="hor-scroll">
                <?php if ($_group['description']): ?>
                    <p style="font-style: italic;"><?php echo $this->escapeHtml($_group['description']); ?></p>
                <?php endif; ?>
                <table cellspacing="0" class="form-list">
                    <tbody>
                    <?php foreach ($_group['actions'] as $_action): ?>
                        <tr>
                            <td class="label"><label><?php echo $this->escapeHtml($_action['label']); ?></label></td>
                            <td class="value">
                                <?php echo $_action['button']; ?>
                                <?php if ($_action['note']): ?>
                                    <p class="note"><?php echo $this->escapeHtml($_action['note']); ?></p>
                                <?php endif; ?>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        </div>
    <?php endforeach; ?>
</div>
