<?php
/**
 * created : 2014
 *
 * @category  Ayaline
 * @package   Ayaline_XXXX
 * @author    aYaline
 * @copyright Ayaline - 2014 - http://magento-shop.ayaline.com
 * @license   http://shop.ayaline.com/magento/fr/conditions-generales-de-vente.html
 */

/** @var $this Ayaline_Core_Block_Adminhtml_Widget_Grids */
?>

<div class="content-header">
    <table cellspacing="0">
        <tr>
            <td style="<?php echo $this->getHeaderWidth(); ?>"><?php echo $this->getHeaderHtml(); ?></td>
            <td class="form-buttons"><?php echo $this->getButtonsHtml(); ?></td>
        </tr>
    </table>
</div>

<div>
    <?php echo $this->getGridsHtml(); ?>
</div>