<?php
/**
 * created : 10/03/2011
 *
 * @category  Ayaline
 * @package   Ayaline_Shop
 * @author    aYaline
 * @copyright Ayaline - 2012 - http://magento-shop.ayaline.com
 * @license   http://shop.ayaline.com/magento/fr/conditions-generales-de-vente.html
 */
?>
<?php
if (Mage::app()->getRequest()->isSecure()) {
    $url = 'https://maps.google.com/maps/api/js?sensor=false&callback=initialize';
} else {
    $url = 'http://maps.google.com/maps/api/js?sensor=false&callback=initialize';
}
?>
<script type="text/javascript">
    //<![CDATA[
    var map;

    function initialize() {
        var optZoom = 10;
        var optLatitude = 46.227638;
        var optLongitude = 2.213749;

        // Try W3C Geolocation (Preferred)
        if (navigator.geolocation) {
            //navigator.geolocation.getCurrentPosition(success_callback_function,errorCallback );
            initializeMap(optLatitude, optLongitude, optZoom);
            // Try Google Gears Geolocation
        } else if (google.gears) {
            browserSupportFlag = true;
            var geo = google.gears.factory.create('beta.geolocation');
            //geo.geolocation.getCurrentPosition(success_callback_function,errorCallback );
            initializeMap(optLatitude, optLongitude, optZoom);
            // Browser doesn't support Geolocation
        } else {
            initializeMap(optLatitude, optLongitude, optZoom);
        }
    }

    function success_callback_function(position) {
        initializeMap(position.coords.latitude, position.coords.longitude, 10);
    }

    function errorCallback(position) {
        initializeMap(optLatitude, optLongitude, optZoom);
    }

    function initializeMap(optLatitude, optLongitude, optZoom) {
        // latitude 15.7 à 16.6 longitude -62 à -60.9 ==> GUADELOUPE
        if (optLatitude > 15.7 && optLatitude < 16.6 && optLongitude > -62 && optLongitude < -60.9) {
            // latitude 15.7 à 16.6 longitude -62 à -60.9 ==> GUADELOUPE
            optLatitude = 15.416615;
            optLongitude = -61.375122;
            optZoom = 8;
        } else if (optLatitude > 14.3 && optLatitude < 15 && optLongitude > -61.3 && optLongitude < -60.7) {
            // latitude 14.3 à 15 longitude -61.3 à -60.7 ==> MARTINIQUE
            optLatitude = 15.416615;
            optLongitude = -61.375122;
            optZoom = 8;
        } else if (optLatitude > 2 && optLatitude < 5.8 && optLongitude > -54.7 && optLongitude < -51.5) {
            // latitude 2 à 5.8 longitude -54.7 à -51.5 ==> GUYANE
            optLatitude = 4.056056;
            optLongitude = -53.300171;
            optZoom = 8;
        } else if (optLatitude > -21.4 && optLatitude < -20.8 && optLongitude > 55.2 && optLongitude < 55.9) {
            // latitude -21.4 à -20.8 longitude 55.2 à 55.9 ==> REUNION
            optLatitude = -21.1151410;
            optLongitude = 55.5363840;
            optZoom = 10;
        } else {
            // ailleurs => on centre sur la france
            optLatitude = 46.227638;
            optLongitude = 2.213749;
            optZoom = 6;
        }

        var myLatlng = new google.maps.LatLng(optLatitude, optLongitude);
        var myOptions = {
            zoom: optZoom,
            center: myLatlng,
            mapTypeId: google.maps.MapTypeId.ROADMAP
        };
        var map = new google.maps.Map(document.getElementById("map_shops"), myOptions);

        <?php $_nb = 0 ?>
        <?php foreach ($this->getShops() as $shop ) :?>
        positionShop_<?php echo $_nb ?> = new google.maps.LatLng(<?php echo $shop->getLatitude()?>, <?php echo $shop->getLongitude()?>);

        <?php if($shop->getMarker()) : ?>
        var markerImage_<?php echo $_nb ?> = new google.maps.MarkerImage('<?php echo Mage::getBaseUrl('media').Ayaline_Shop_Model_Shop::PICTO_PATH_FOLDER.'/'.$shop->getMarker()?>',
            new google.maps.Size(30, 30),
            new google.maps.Point(0, 0)
        );
        console.log(markerImage_<?php echo $_nb ?>);
        marker<?php echo $_nb ?> = new google.maps.Marker({
            map: map,
            draggable: false,
            position: positionShop_<?php echo $_nb ?>,
            title: '<?php echo addslashes ( $shop->getTitle()) ?>',
            icon: markerImage_<?php echo $_nb ?>
        });

        <?php else : ?>
        marker<?php echo $_nb ?> = new google.maps.Marker({
            map: map,
            draggable: false,
            position: positionShop_<?php echo $_nb ?>,
            title: '<?php echo addslashes ( $shop->getTitle()) ?>'
        });
        <?php endif; ?>

        google.maps.event.addListener(marker<?php echo $_nb ?>, 'click',
            function () {
                var myWindowOptions = {
                    content: '<h6><?php echo addslashes ( $shop->getTitle() ) ?></h6>' +
                    <?php if($shop->getStreet1()) : ?>
                    '<div class="shop-view-address-line"><?php echo addslashes ( $shop->getStreet1() )?></div>' +
                    <?php endif;?>

                    <?php if($shop->getStreet2()) : ?>
                    '<div class="shop-view-address-line"><?php echo addslashes ( $shop->getStreet2() )?></div>' +
                    <?php endif;?>
                    '<div class="shop-view-address-line"><?php echo $shop->getPostcode()?>&nbsp;<?php echo addslashes ( $shop->getCity() )?></div>' +
                    <?php if($shop->getTelephone()) : ?>
                    '<div class="shop-view-address-line"><?php echo $this->__('Tel')?>&nbsp;:&nbsp;<?php echo $shop->getTelephone()?></div>' +
                    <?php endif;?>
                    <?php if($shop->getFax()) : ?>
                    '<div class="shop-view-address-line"><?php echo $this->__('Fax')?>&nbsp;:&nbsp;<?php echo $shop->getFax()?></div>' +
                    <?php endif;?>
                    <?php if($shop->getEmail()) : ?>
                    <?php $_emails = explode("\n", $shop->getEmail()); ?>
                    <?php foreach($_emails as $_email): ?>
                    <?php if(!empty($_email)): ?>
                    '<div class="shop-view-address-line"><?php echo $_email; ?></div>' +
                    <?php endif; ?>
                    <?php endforeach; ?>
                    <?php endif;?>
                    <?php if($shop->getWebsite()) : ?>
                    <?php $_websites = explode("\n", $shop->getWebsite()); ?>
                    <?php foreach($_websites as $_website): ?>
                    <?php if(!empty($_website)): ?>
                    '<div class="shop-view-address-line">' +
                    '<a href="<?php echo $_website; ?>" target="_bank">' +
                    '<?php echo $_website; ?>' +
                    '</a>' +
                    '</div>' +
                    <?php endif; ?>
                    <?php endforeach; ?>
                    <?php endif;?>
                    '<br>' +
                    '<p>' +
                    '<a href="<?php echo $this->getViewUrl($shop->getId()) ?>" title="<?php echo $this->__('More Informations') ?>">' +
                    '<?php echo $this->__('More Informations') ?>' +
                    '</a>' +
                    '</p>'
                };
                var myInfoWindow = new google.maps.InfoWindow(myWindowOptions);
                myInfoWindow.open(map, marker<?php echo $_nb ?>);
            });
        <?php $_nb++;?>
        <?php //break;?>
        <?php endforeach;?>
    }

    function loadScript() {
        var script = document.createElement("script");
        script.type = "text/javascript";
        script.src = "<?php echo $url; ?>";
        document.body.appendChild(script);
    }

    window.onload = loadScript;
    //]]>
</script>

<div id="map_shops"></div>
