<?php
/**
 * created: 2014
 *
 * @category  Ayaline
 * @package   Ayaline_XXXX
 * @author    aYaline
 * @copyright Ayaline - 2014 - http://magento-shop.ayaline.com
 * @license   http://shop.ayaline.com/magento/fr/conditions-generales-de-vente.html
 */

/** @var $this Ayaline_GoogleUniversalAnalytics_Block_Tag */

?>

<!-- Google Analytics -->
<?php if (Mage::getSingleton('ayaline_gua/system_config')->canUseAlternativeAsynchronousSnippet()): ?>
    <script async src="<?php echo $this->getAnalyticsUrl(); ?>"></script>
<?php endif; ?>
<script>
    <?php if (Mage::getSingleton('ayaline_gua/system_config')->canUseAlternativeAsynchronousSnippet()): ?>
    window.ga = window.ga || function () {
            (ga.q = ga.q || []).push(arguments)
        };
    ga.l = +new Date;
    <?php else: ?>
    (function (i, s, o, g, r, a, m) {
        i['GoogleAnalyticsObject'] = r;
        i[r] = i[r] || function () {
                (i[r].q = i[r].q || []).push(arguments)
            }, i[r].l = 1 * new Date();
        a = s.createElement(o),
            m = s.getElementsByTagName(o)[0];
        a.async = 1;
        a.src = g;
        m.parentNode.insertBefore(a, m)
    })(window, document, 'script', '<?php echo $this->getAnalyticsUrl(); ?>', 'ga');
    <?php endif; ?>
    <?php if ($this->canUseDebugTrace()): ?>
    window.ga_debug = {trace: true};
    <?php endif; ?>
    <?php
        echo $this->getCreate();
        echo $this->getAnonymizeIp();
        echo $this->getForceSsl();
        echo $this->getUserId();
    ?>
    ga('send', 'pageview');
    <?php echo $this->getEcommerce(); ?>
    <?php echo $this->getOnepageTracking();?>
</script>
<!-- End Google Analytics -->
