<?php /** @var $this Mage_Core_Block_Template */ ?>


<div class="nav-container">
    <nav class="navbar navbar-default">
        <div class="navbar-header">
            <button type="button" data-target="#navbarCollapse" data-toggle="collapse" class="navbar-toggle">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </div>
        <div id="navbarCollapse" class="collapse navbar-collapse">
            <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('entete-menu')->toHtml(); ?>
            <?php echo $this->getChildHtml('store_language'); ?>
            <ul class="home">
                <li>
                    <a href="<?php echo Mage::getBaseUrl();?>" class="level-top"><span><?php echo $this->__("Home");?></span></a>
                </li>
            </ul>
            <?php echo $this->getChildHtml('catalog.topnav'); ?>
            <ul>
                <li><a href="<?php echo Mage::helper('sabre_configuration')->getPageUrlByIdentifier('marque')?>"><?php echo $this->__("The spirit Sabre")?></a></li>
                <li><a href="<?php echo $this->escapeUrl($this->getUrl('shop/index/index')) ?>"><?php echo $this->__('Our Shops')?></a></li>
                <li><a href="<?php echo Mage::helper('sabre_configuration')->getPageUrlByIdentifier('service-client')?>"><?php echo $this->__('Customer Service')?></a></li>
            </ul>
            <ul>
                <li class="compte"><a href="<?php echo Mage::getUrl('customer/account'); ?>"><?php echo $this->__('My Account')?></a></li>
                <li class="panier"><a href="<?php echo Mage::getUrl('checkout/cart'); ?>"><?php echo $this->__('My Cart')?></a></li>
            </ul>
        </div>
    </nav>

</div>
